name: womensafteyhackfair
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  background_location: ^0.7.0
  carousel_slider: ^5.1.1
  contacts_service: ^0.6.3
  flutter_background_service: ^5.0.5
  flutter_launcher_icons: ^0.9.2
  flutter_phone_direct_caller: ^2.0.0
  flutter_slidable: ^4.0.1
  flutter_spinkit: ^5.1.0
  webview_flutter: ^4.4.2
  fluttertoast: ^8.0.8
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  google_fonts: ^6.3.1
  location: ^5.0.3
  lottie: ^1.2.1
  permission_handler: ^8.1.6
  pinput: ^1.2.1
  shake: ^1.0.1
  shared_preferences: ^2.0.5
  sms_advanced: ^1.0.2
  telephony: ^0.1.4
  url_launcher: ^6.0.10
  vibration: ^1.7.3
  workmanager: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  image_path: "assets/logo.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/
